export default {
  logo: require("../assets/images/i2c-logo.png"),
  mobileGroup: require("../assets/images/mobile-group.png"),
  dolorBottom: require("../assets/images/dolor-bottom.svg"),
  user1: require("../assets/images/user1.svg"),
  user2: require("../assets/images/user2.svg"),
  user3: require("../assets/images/user3.svg"),
  support: require("../assets/images/24-7-support.svg"),
  awards: require("../assets/images/awards.svg"),
  reviews: require("../assets/images/reviews.svg"),
  trusted: require("../assets/images/trusted.svg"),
  microsoft: require("../assets/images/microsoft.svg"),
  chevronLeft: require("../assets/images/chevron-left.svg"),
  twiter: require("../assets/images/twiter.svg"),
  cocacolla: require("../assets/images/cocacolla.svg"),
  chevronRight: require("../assets/images/chevron-right.svg"),
  group2: require("../assets/images/group2.svg"),
  separator: require("../assets/images/separator.svg"),
};
